import type {
  Property,
  Channel,
  ChannelActivity,
  PriceRecord,
  AvailabilityRecord,
  Alert,
  Evidence,
  Mapping,
  Settings,
  KPIData,
} from './types';

// Properties
export const properties: Property[] = [
  {
    id: 'prop-1',
    name: 'Grand Marina Resort & Spa',
    city: 'Phuket',
    country: 'Thailand',
    activeChannels: ['booking', 'agoda', 'airbnb', 'expedia'],
    roomTypes: ['Deluxe Ocean View', 'Premium Suite', 'Pool Villa', 'Standard Room'],
    ratePlans: ['Flexible', 'Non-refundable', 'Breakfast Included', 'Long Stay'],
    lastSync: '2026-05-17T08:45:00Z',
    alertCount: 3,
    healthStatus: 'warning',
  },
  {
    id: 'prop-2',
    name: 'Urban Boutique Hotel',
    city: 'Bangkok',
    country: 'Thailand',
    activeChannels: ['booking', 'agoda', 'expedia'],
    roomTypes: ['Superior Room', 'Deluxe Room', 'Executive Suite'],
    ratePlans: ['Flexible', 'Non-refundable', 'Member Rate'],
    lastSync: '2026-05-17T09:12:00Z',
    alertCount: 0,
    healthStatus: 'healthy',
  },
  {
    id: 'prop-3',
    name: 'Seaside Villas Collection',
    city: 'Bali',
    country: 'Indonesia',
    activeChannels: ['booking', 'airbnb', 'vrbo'],
    roomTypes: ['1BR Villa', '2BR Villa', '3BR Villa', 'Private Pool Villa'],
    ratePlans: ['Flexible', 'Non-refundable', 'Weekly Discount'],
    lastSync: '2026-05-17T07:30:00Z',
    alertCount: 5,
    healthStatus: 'critical',
  },
  {
    id: 'prop-4',
    name: 'Mountain View Lodge',
    city: 'Chiang Mai',
    country: 'Thailand',
    activeChannels: ['booking', 'agoda'],
    roomTypes: ['Mountain View Room', 'Garden Bungalow', 'Family Suite'],
    ratePlans: ['Flexible', 'Breakfast Included'],
    lastSync: '2026-05-17T09:00:00Z',
    alertCount: 1,
    healthStatus: 'healthy',
  },
  {
    id: 'prop-5',
    name: 'City Center Apartments',
    city: 'Singapore',
    country: 'Singapore',
    activeChannels: ['booking', 'airbnb', 'agoda', 'expedia'],
    roomTypes: ['Studio', '1BR Apartment', '2BR Apartment', 'Penthouse'],
    ratePlans: ['Flexible', 'Non-refundable', 'Monthly Rate'],
    lastSync: '2026-05-16T23:45:00Z',
    alertCount: 2,
    healthStatus: 'warning',
  },
  {
    id: 'prop-6',
    name: 'Heritage Mansion',
    city: 'Penang',
    country: 'Malaysia',
    activeChannels: ['booking', 'agoda', 'trip'],
    roomTypes: ['Heritage Room', 'Colonial Suite', 'Garden Room'],
    ratePlans: ['Flexible', 'Non-refundable'],
    lastSync: '2026-05-17T08:00:00Z',
    alertCount: 0,
    healthStatus: 'healthy',
  },
];

// Channels
const channelActivities: ChannelActivity[] = [
  { id: 'act-1', channelId: 'booking', action: 'Price scrape completed', timestamp: '2026-05-17T09:15:00Z', status: 'success' },
  { id: 'act-2', channelId: 'booking', action: 'Availability sync', timestamp: '2026-05-17T09:10:00Z', status: 'success' },
  { id: 'act-3', channelId: 'agoda', action: 'Price scrape completed', timestamp: '2026-05-17T09:12:00Z', status: 'success' },
  { id: 'act-4', channelId: 'agoda', action: 'Rate extraction failed', timestamp: '2026-05-17T08:45:00Z', status: 'failed' },
  { id: 'act-5', channelId: 'airbnb', action: 'Listing sync', timestamp: '2026-05-17T09:00:00Z', status: 'success' },
  { id: 'act-6', channelId: 'expedia', action: 'Price scrape pending', timestamp: '2026-05-17T09:20:00Z', status: 'pending' },
];

export const channels: Channel[] = [
  {
    id: 'booking',
    name: 'Booking.com',
    propertiesTracked: 6,
    lastScrape: '2026-05-17T09:15:00Z',
    successRate: 98.5,
    activeIssues: 2,
    status: 'healthy',
    recentActivity: channelActivities.filter(a => a.channelId === 'booking'),
  },
  {
    id: 'agoda',
    name: 'Agoda',
    propertiesTracked: 5,
    lastScrape: '2026-05-17T09:12:00Z',
    successRate: 94.2,
    activeIssues: 3,
    status: 'warning',
    recentActivity: channelActivities.filter(a => a.channelId === 'agoda'),
  },
  {
    id: 'airbnb',
    name: 'Airbnb',
    propertiesTracked: 3,
    lastScrape: '2026-05-17T09:00:00Z',
    successRate: 99.1,
    activeIssues: 1,
    status: 'healthy',
    recentActivity: channelActivities.filter(a => a.channelId === 'airbnb'),
  },
  {
    id: 'expedia',
    name: 'Expedia',
    propertiesTracked: 3,
    lastScrape: '2026-05-17T08:30:00Z',
    successRate: 87.3,
    activeIssues: 4,
    status: 'critical',
    recentActivity: channelActivities.filter(a => a.channelId === 'expedia'),
  },
  {
    id: 'vrbo',
    name: 'VRBO',
    propertiesTracked: 1,
    lastScrape: '2026-05-17T07:45:00Z',
    successRate: 96.0,
    activeIssues: 0,
    status: 'healthy',
    recentActivity: [],
  },
  {
    id: 'trip',
    name: 'Trip.com',
    propertiesTracked: 1,
    lastScrape: '2026-05-17T08:00:00Z',
    successRate: 91.5,
    activeIssues: 1,
    status: 'warning',
    recentActivity: [],
  },
];

// Price Records
export const priceRecords: PriceRecord[] = [
  {
    id: 'price-1',
    propertyId: 'prop-1',
    propertyName: 'Grand Marina Resort & Spa',
    channelId: 'booking',
    channelName: 'Booking.com',
    roomType: 'Deluxe Ocean View',
    ratePlan: 'Flexible',
    stayDate: '2026-05-20',
    displayPrice: 4500,
    referencePrice: 4200,
    priceDelta: 300,
    deltaPercent: 7.14,
    currency: 'THB',
    capturedAt: '2026-05-17T09:15:00Z',
    parityStatus: 'warning',
  },
  {
    id: 'price-2',
    propertyId: 'prop-1',
    propertyName: 'Grand Marina Resort & Spa',
    channelId: 'agoda',
    channelName: 'Agoda',
    roomType: 'Deluxe Ocean View',
    ratePlan: 'Flexible',
    stayDate: '2026-05-20',
    displayPrice: 4100,
    referencePrice: 4200,
    priceDelta: -100,
    deltaPercent: -2.38,
    currency: 'THB',
    capturedAt: '2026-05-17T09:12:00Z',
    parityStatus: 'match',
  },
  {
    id: 'price-3',
    propertyId: 'prop-1',
    propertyName: 'Grand Marina Resort & Spa',
    channelId: 'airbnb',
    channelName: 'Airbnb',
    roomType: 'Pool Villa',
    ratePlan: 'Flexible',
    stayDate: '2026-05-20',
    displayPrice: 12500,
    referencePrice: 10000,
    priceDelta: 2500,
    deltaPercent: 25.0,
    currency: 'THB',
    capturedAt: '2026-05-17T09:00:00Z',
    parityStatus: 'mismatch',
  },
  {
    id: 'price-4',
    propertyId: 'prop-2',
    propertyName: 'Urban Boutique Hotel',
    channelId: 'booking',
    channelName: 'Booking.com',
    roomType: 'Superior Room',
    ratePlan: 'Non-refundable',
    stayDate: '2026-05-21',
    displayPrice: 2800,
    referencePrice: 2800,
    priceDelta: 0,
    deltaPercent: 0,
    currency: 'THB',
    capturedAt: '2026-05-17T09:15:00Z',
    parityStatus: 'match',
  },
  {
    id: 'price-5',
    propertyId: 'prop-3',
    propertyName: 'Seaside Villas Collection',
    channelId: 'booking',
    channelName: 'Booking.com',
    roomType: '2BR Villa',
    ratePlan: 'Weekly Discount',
    stayDate: '2026-05-22',
    displayPrice: 350,
    referencePrice: 280,
    priceDelta: 70,
    deltaPercent: 25.0,
    currency: 'USD',
    capturedAt: '2026-05-17T07:30:00Z',
    parityStatus: 'mismatch',
  },
  {
    id: 'price-6',
    propertyId: 'prop-3',
    propertyName: 'Seaside Villas Collection',
    channelId: 'airbnb',
    channelName: 'Airbnb',
    roomType: 'Private Pool Villa',
    ratePlan: 'Flexible',
    stayDate: '2026-05-23',
    displayPrice: 480,
    referencePrice: 450,
    priceDelta: 30,
    deltaPercent: 6.67,
    currency: 'USD',
    capturedAt: '2026-05-17T09:00:00Z',
    parityStatus: 'warning',
  },
  {
    id: 'price-7',
    propertyId: 'prop-4',
    propertyName: 'Mountain View Lodge',
    channelId: 'agoda',
    channelName: 'Agoda',
    roomType: 'Garden Bungalow',
    ratePlan: 'Breakfast Included',
    stayDate: '2026-05-24',
    displayPrice: 3200,
    referencePrice: 3200,
    priceDelta: 0,
    deltaPercent: 0,
    currency: 'THB',
    capturedAt: '2026-05-17T09:12:00Z',
    parityStatus: 'match',
  },
  {
    id: 'price-8',
    propertyId: 'prop-5',
    propertyName: 'City Center Apartments',
    channelId: 'booking',
    channelName: 'Booking.com',
    roomType: '1BR Apartment',
    ratePlan: 'Flexible',
    stayDate: '2026-05-25',
    displayPrice: 220,
    referencePrice: 200,
    priceDelta: 20,
    deltaPercent: 10.0,
    currency: 'SGD',
    capturedAt: '2026-05-16T23:45:00Z',
    parityStatus: 'warning',
  },
  {
    id: 'price-9',
    propertyId: 'prop-5',
    propertyName: 'City Center Apartments',
    channelId: 'expedia',
    channelName: 'Expedia',
    roomType: 'Penthouse',
    ratePlan: 'Non-refundable',
    stayDate: '2026-05-26',
    displayPrice: 650,
    referencePrice: 500,
    priceDelta: 150,
    deltaPercent: 30.0,
    currency: 'SGD',
    capturedAt: '2026-05-17T08:30:00Z',
    parityStatus: 'mismatch',
  },
  {
    id: 'price-10',
    propertyId: 'prop-6',
    propertyName: 'Heritage Mansion',
    channelId: 'booking',
    channelName: 'Booking.com',
    roomType: 'Colonial Suite',
    ratePlan: 'Flexible',
    stayDate: '2026-05-27',
    displayPrice: 450,
    referencePrice: 450,
    priceDelta: 0,
    deltaPercent: 0,
    currency: 'MYR',
    capturedAt: '2026-05-17T08:00:00Z',
    parityStatus: 'match',
  },
];

// Availability Records
export const availabilityRecords: AvailabilityRecord[] = [
  { id: 'avail-1', propertyId: 'prop-1', propertyName: 'Grand Marina Resort & Spa', channelId: 'booking', channelName: 'Booking.com', roomType: 'Deluxe Ocean View', stayDate: '2026-05-20', status: 'available', capturedAt: '2026-05-17T09:15:00Z' },
  { id: 'avail-2', propertyId: 'prop-1', propertyName: 'Grand Marina Resort & Spa', channelId: 'booking', channelName: 'Booking.com', roomType: 'Deluxe Ocean View', stayDate: '2026-05-21', status: 'available', capturedAt: '2026-05-17T09:15:00Z' },
  { id: 'avail-3', propertyId: 'prop-1', propertyName: 'Grand Marina Resort & Spa', channelId: 'booking', channelName: 'Booking.com', roomType: 'Deluxe Ocean View', stayDate: '2026-05-22', status: 'sold_out', capturedAt: '2026-05-17T09:15:00Z' },
  { id: 'avail-4', propertyId: 'prop-1', propertyName: 'Grand Marina Resort & Spa', channelId: 'agoda', channelName: 'Agoda', roomType: 'Deluxe Ocean View', stayDate: '2026-05-22', status: 'available', capturedAt: '2026-05-17T09:12:00Z' },
  { id: 'avail-5', propertyId: 'prop-3', propertyName: 'Seaside Villas Collection', channelId: 'booking', channelName: 'Booking.com', roomType: '2BR Villa', stayDate: '2026-05-20', status: 'stale', capturedAt: '2026-05-15T12:00:00Z' },
  { id: 'avail-6', propertyId: 'prop-3', propertyName: 'Seaside Villas Collection', channelId: 'airbnb', channelName: 'Airbnb', roomType: 'Private Pool Villa', stayDate: '2026-05-21', status: 'mismatch', capturedAt: '2026-05-17T09:00:00Z' },
  { id: 'avail-7', propertyId: 'prop-5', propertyName: 'City Center Apartments', channelId: 'booking', channelName: 'Booking.com', roomType: '1BR Apartment', stayDate: '2026-05-23', status: 'sold_out', capturedAt: '2026-05-16T23:45:00Z' },
  { id: 'avail-8', propertyId: 'prop-5', propertyName: 'City Center Apartments', channelId: 'airbnb', channelName: 'Airbnb', roomType: '1BR Apartment', stayDate: '2026-05-23', status: 'available', capturedAt: '2026-05-17T09:00:00Z' },
  { id: 'avail-9', propertyId: 'prop-2', propertyName: 'Urban Boutique Hotel', channelId: 'booking', channelName: 'Booking.com', roomType: 'Superior Room', stayDate: '2026-05-24', status: 'available', capturedAt: '2026-05-17T09:15:00Z' },
  { id: 'avail-10', propertyId: 'prop-4', propertyName: 'Mountain View Lodge', channelId: 'agoda', channelName: 'Agoda', roomType: 'Garden Bungalow', stayDate: '2026-05-25', status: 'available', capturedAt: '2026-05-17T09:12:00Z' },
];

// Alerts
export const alerts: Alert[] = [
  {
    id: 'alert-1',
    severity: 'critical',
    title: 'Significant price parity violation',
    description: 'Pool Villa price on Airbnb is 25% higher than reference price',
    propertyId: 'prop-1',
    propertyName: 'Grand Marina Resort & Spa',
    channelId: 'airbnb',
    channelName: 'Airbnb',
    roomType: 'Pool Villa',
    issueType: 'parity',
    firstSeen: '2026-05-17T06:00:00Z',
    lastSeen: '2026-05-17T09:00:00Z',
    status: 'active',
    hasEvidence: true,
  },
  {
    id: 'alert-2',
    severity: 'high',
    title: 'Availability mismatch detected',
    description: 'Booking.com shows sold out but Agoda shows available for May 22',
    propertyId: 'prop-1',
    propertyName: 'Grand Marina Resort & Spa',
    channelId: 'booking',
    channelName: 'Booking.com',
    roomType: 'Deluxe Ocean View',
    issueType: 'availability',
    firstSeen: '2026-05-17T08:00:00Z',
    lastSeen: '2026-05-17T09:15:00Z',
    status: 'active',
    hasEvidence: true,
  },
  {
    id: 'alert-3',
    severity: 'medium',
    title: 'Price warning threshold exceeded',
    description: 'Deluxe Ocean View on Booking.com is 7% above reference',
    propertyId: 'prop-1',
    propertyName: 'Grand Marina Resort & Spa',
    channelId: 'booking',
    channelName: 'Booking.com',
    roomType: 'Deluxe Ocean View',
    issueType: 'parity',
    firstSeen: '2026-05-17T07:00:00Z',
    lastSeen: '2026-05-17T09:15:00Z',
    status: 'active',
    hasEvidence: false,
  },
  {
    id: 'alert-4',
    severity: 'critical',
    title: 'Stale data - no scrape in 48+ hours',
    description: '2BR Villa availability data is over 48 hours old',
    propertyId: 'prop-3',
    propertyName: 'Seaside Villas Collection',
    channelId: 'booking',
    channelName: 'Booking.com',
    roomType: '2BR Villa',
    issueType: 'stale_data',
    firstSeen: '2026-05-16T12:00:00Z',
    lastSeen: '2026-05-17T09:00:00Z',
    status: 'active',
    hasEvidence: false,
  },
  {
    id: 'alert-5',
    severity: 'critical',
    title: 'Critical price disparity',
    description: '2BR Villa price on Booking.com is 25% higher than reference',
    propertyId: 'prop-3',
    propertyName: 'Seaside Villas Collection',
    channelId: 'booking',
    channelName: 'Booking.com',
    roomType: '2BR Villa',
    issueType: 'parity',
    firstSeen: '2026-05-17T05:00:00Z',
    lastSeen: '2026-05-17T07:30:00Z',
    status: 'active',
    hasEvidence: true,
  },
  {
    id: 'alert-6',
    severity: 'high',
    title: 'Scrape failures on Expedia',
    description: 'Multiple scrape failures detected for Expedia channel',
    propertyId: 'prop-5',
    propertyName: 'City Center Apartments',
    channelId: 'expedia',
    channelName: 'Expedia',
    issueType: 'scrape_failure',
    firstSeen: '2026-05-17T04:00:00Z',
    lastSeen: '2026-05-17T08:30:00Z',
    status: 'active',
    hasEvidence: false,
  },
  {
    id: 'alert-7',
    severity: 'critical',
    title: 'Penthouse price mismatch',
    description: 'Penthouse on Expedia is 30% above reference price',
    propertyId: 'prop-5',
    propertyName: 'City Center Apartments',
    channelId: 'expedia',
    channelName: 'Expedia',
    roomType: 'Penthouse',
    issueType: 'parity',
    firstSeen: '2026-05-17T08:30:00Z',
    lastSeen: '2026-05-17T08:30:00Z',
    status: 'active',
    hasEvidence: true,
  },
  {
    id: 'alert-8',
    severity: 'low',
    title: 'Minor price variance',
    description: 'Garden Bungalow shows 5% variance on historical comparison',
    propertyId: 'prop-4',
    propertyName: 'Mountain View Lodge',
    channelId: 'agoda',
    channelName: 'Agoda',
    roomType: 'Garden Bungalow',
    issueType: 'parity',
    firstSeen: '2026-05-16T18:00:00Z',
    lastSeen: '2026-05-17T09:12:00Z',
    status: 'acknowledged',
    hasEvidence: false,
  },
  {
    id: 'alert-9',
    severity: 'medium',
    title: 'Availability sync anomaly',
    description: 'Private Pool Villa shows mismatch between channels',
    propertyId: 'prop-3',
    propertyName: 'Seaside Villas Collection',
    channelId: 'airbnb',
    channelName: 'Airbnb',
    roomType: 'Private Pool Villa',
    issueType: 'availability',
    firstSeen: '2026-05-17T08:00:00Z',
    lastSeen: '2026-05-17T09:00:00Z',
    status: 'active',
    hasEvidence: true,
  },
  {
    id: 'alert-10',
    severity: 'high',
    title: 'Sold out discrepancy',
    description: '1BR Apartment shows sold out on Booking but available on Airbnb',
    propertyId: 'prop-5',
    propertyName: 'City Center Apartments',
    channelId: 'booking',
    channelName: 'Booking.com',
    roomType: '1BR Apartment',
    issueType: 'availability',
    firstSeen: '2026-05-17T00:00:00Z',
    lastSeen: '2026-05-17T09:00:00Z',
    status: 'active',
    hasEvidence: true,
  },
];

// Evidence
export const evidenceItems: Evidence[] = [
  {
    id: 'ev-1',
    propertyId: 'prop-1',
    propertyName: 'Grand Marina Resort & Spa',
    channelId: 'airbnb',
    channelName: 'Airbnb',
    roomType: 'Pool Villa',
    capturedAt: '2026-05-17T09:00:00Z',
    screenshotUrl: '/evidence/ev-1.png',
    thumbnailUrl: '/evidence/ev-1-thumb.png',
    extractedData: {
      price: 12500,
      currency: 'THB',
      availability: 'Available',
      dates: 'May 20-21, 2026',
    },
    sourcePageUrl: 'https://airbnb.com/rooms/12345',
    sourcePageLabel: 'Airbnb Listing Page',
    status: 'verified',
    relatedAlertIds: ['alert-1'],
  },
  {
    id: 'ev-2',
    propertyId: 'prop-1',
    propertyName: 'Grand Marina Resort & Spa',
    channelId: 'booking',
    channelName: 'Booking.com',
    roomType: 'Deluxe Ocean View',
    capturedAt: '2026-05-17T09:15:00Z',
    screenshotUrl: '/evidence/ev-2.png',
    thumbnailUrl: '/evidence/ev-2-thumb.png',
    extractedData: {
      price: 4500,
      currency: 'THB',
      availability: 'Sold Out',
      dates: 'May 22, 2026',
    },
    sourcePageUrl: 'https://booking.com/hotel/th/grand-marina',
    sourcePageLabel: 'Booking.com Hotel Page',
    status: 'verified',
    relatedAlertIds: ['alert-2'],
  },
  {
    id: 'ev-3',
    propertyId: 'prop-3',
    propertyName: 'Seaside Villas Collection',
    channelId: 'booking',
    channelName: 'Booking.com',
    roomType: '2BR Villa',
    capturedAt: '2026-05-17T07:30:00Z',
    screenshotUrl: '/evidence/ev-3.png',
    thumbnailUrl: '/evidence/ev-3-thumb.png',
    extractedData: {
      price: 350,
      currency: 'USD',
      availability: 'Available',
      dates: 'May 22, 2026',
    },
    sourcePageUrl: 'https://booking.com/hotel/id/seaside-villas',
    sourcePageLabel: 'Booking.com Hotel Page',
    status: 'flagged',
    relatedAlertIds: ['alert-5'],
  },
  {
    id: 'ev-4',
    propertyId: 'prop-5',
    propertyName: 'City Center Apartments',
    channelId: 'expedia',
    channelName: 'Expedia',
    roomType: 'Penthouse',
    capturedAt: '2026-05-17T08:30:00Z',
    screenshotUrl: '/evidence/ev-4.png',
    thumbnailUrl: '/evidence/ev-4-thumb.png',
    extractedData: {
      price: 650,
      currency: 'SGD',
      availability: 'Available',
      dates: 'May 26, 2026',
    },
    sourcePageUrl: 'https://expedia.com/hotel/sg/city-center',
    sourcePageLabel: 'Expedia Hotel Page',
    status: 'pending',
    relatedAlertIds: ['alert-7'],
  },
  {
    id: 'ev-5',
    propertyId: 'prop-3',
    propertyName: 'Seaside Villas Collection',
    channelId: 'airbnb',
    channelName: 'Airbnb',
    roomType: 'Private Pool Villa',
    capturedAt: '2026-05-17T09:00:00Z',
    screenshotUrl: '/evidence/ev-5.png',
    thumbnailUrl: '/evidence/ev-5-thumb.png',
    extractedData: {
      price: 480,
      currency: 'USD',
      availability: 'Available',
      dates: 'May 21, 2026',
    },
    sourcePageUrl: 'https://airbnb.com/rooms/67890',
    sourcePageLabel: 'Airbnb Listing Page',
    status: 'verified',
    relatedAlertIds: ['alert-9'],
  },
  {
    id: 'ev-6',
    propertyId: 'prop-5',
    propertyName: 'City Center Apartments',
    channelId: 'booking',
    channelName: 'Booking.com',
    roomType: '1BR Apartment',
    capturedAt: '2026-05-17T09:00:00Z',
    screenshotUrl: '/evidence/ev-6.png',
    thumbnailUrl: '/evidence/ev-6-thumb.png',
    extractedData: {
      price: 220,
      currency: 'SGD',
      availability: 'Sold Out',
      dates: 'May 23, 2026',
    },
    sourcePageUrl: 'https://booking.com/hotel/sg/city-center',
    sourcePageLabel: 'Booking.com Hotel Page',
    status: 'verified',
    relatedAlertIds: ['alert-10'],
  },
];

// Mappings
export const mappings: Mapping[] = [
  {
    id: 'map-1',
    propertyId: 'prop-1',
    propertyName: 'Grand Marina Resort & Spa',
    otaPropertyId: 'bcom-12345',
    otaPropertyName: 'Grand Marina Resort & Spa Phuket',
    channelId: 'booking',
    channelName: 'Booking.com',
    roomTypeId: 'rt-1',
    roomTypeName: 'Deluxe Ocean View',
    otaRoomId: 'bcom-rm-001',
    otaRoomName: 'Deluxe Room with Ocean View',
    ratePlanId: 'rp-1',
    ratePlanName: 'Flexible',
    otaRatePlanId: 'bcom-rp-flex',
    otaRatePlanName: 'Flexible Rate',
    status: 'active',
    lastVerified: '2026-05-17T00:00:00Z',
  },
  {
    id: 'map-2',
    propertyId: 'prop-1',
    propertyName: 'Grand Marina Resort & Spa',
    otaPropertyId: 'agoda-67890',
    otaPropertyName: 'Grand Marina Resort Phuket',
    channelId: 'agoda',
    channelName: 'Agoda',
    roomTypeId: 'rt-1',
    roomTypeName: 'Deluxe Ocean View',
    otaRoomId: 'agoda-rm-001',
    otaRoomName: 'Deluxe Ocean View Room',
    ratePlanId: 'rp-1',
    ratePlanName: 'Flexible',
    otaRatePlanId: 'agoda-rp-std',
    otaRatePlanName: 'Standard Cancellation',
    status: 'active',
    lastVerified: '2026-05-16T00:00:00Z',
  },
  {
    id: 'map-3',
    propertyId: 'prop-1',
    propertyName: 'Grand Marina Resort & Spa',
    otaPropertyId: 'abnb-villa-001',
    otaPropertyName: 'Luxury Pool Villa at Grand Marina',
    channelId: 'airbnb',
    channelName: 'Airbnb',
    roomTypeId: 'rt-3',
    roomTypeName: 'Pool Villa',
    otaRoomId: 'abnb-unit-001',
    otaRoomName: 'Entire villa',
    ratePlanId: 'rp-1',
    ratePlanName: 'Flexible',
    otaRatePlanId: 'abnb-flex',
    otaRatePlanName: 'Flexible cancellation',
    status: 'active',
    lastVerified: '2026-05-15T00:00:00Z',
  },
  {
    id: 'map-4',
    propertyId: 'prop-3',
    propertyName: 'Seaside Villas Collection',
    otaPropertyId: 'bcom-villas-001',
    otaPropertyName: 'Seaside Villas Bali',
    channelId: 'booking',
    channelName: 'Booking.com',
    roomTypeId: 'rt-villa-2br',
    roomTypeName: '2BR Villa',
    otaRoomId: 'bcom-rm-villa2',
    otaRoomName: 'Two-Bedroom Villa',
    ratePlanId: 'rp-weekly',
    ratePlanName: 'Weekly Discount',
    otaRatePlanId: 'bcom-rp-week',
    otaRatePlanName: 'Weekly Stay Rate',
    status: 'active',
    lastVerified: '2026-05-14T00:00:00Z',
  },
  {
    id: 'map-5',
    propertyId: 'prop-5',
    propertyName: 'City Center Apartments',
    otaPropertyId: 'exp-sg-apt-001',
    otaPropertyName: 'City Center Luxury Apartments Singapore',
    channelId: 'expedia',
    channelName: 'Expedia',
    roomTypeId: 'rt-penthouse',
    roomTypeName: 'Penthouse',
    otaRoomId: 'exp-rm-ph',
    otaRoomName: 'Penthouse Suite',
    ratePlanId: 'rp-nr',
    ratePlanName: 'Non-refundable',
    otaRatePlanId: 'exp-rp-nr',
    otaRatePlanName: 'Non-refundable Rate',
    status: 'pending',
    lastVerified: '2026-05-10T00:00:00Z',
  },
];

// Settings
export const settings: Settings = {
  scrapeProfiles: [
    { id: 'sp-1', name: 'High Frequency', cadenceMinutes: 60, enabled: true, channels: ['booking', 'agoda'] },
    { id: 'sp-2', name: 'Standard', cadenceMinutes: 240, enabled: true, channels: ['airbnb', 'expedia', 'vrbo'] },
    { id: 'sp-3', name: 'Low Frequency', cadenceMinutes: 720, enabled: false, channels: ['trip'] },
  ],
  alertThresholds: {
    parityWarningPercent: 5,
    parityCriticalPercent: 15,
    staleDataHours: 24,
  },
  parityTolerance: 3,
  evidenceRetentionDays: 90,
};

// KPI Data
export const kpiData: KPIData = {
  totalProperties: properties.length,
  trackedChannels: channels.length,
  activeAlerts: alerts.filter(a => a.status === 'active').length,
  scrapeHealthScore: 94.2,
  parityIssues: priceRecords.filter(p => p.parityStatus !== 'match').length,
  soldOutAnomalies: availabilityRecords.filter(a => a.status === 'mismatch' || (a.status === 'sold_out')).length,
};

// Helper functions for filtering
export function getPropertyById(id: string): Property | undefined {
  return properties.find(p => p.id === id);
}

export function getChannelById(id: string): Channel | undefined {
  return channels.find(c => c.id === id);
}

export function getAlertsByProperty(propertyId: string): Alert[] {
  return alerts.filter(a => a.propertyId === propertyId);
}

export function getEvidenceByProperty(propertyId: string): Evidence[] {
  return evidenceItems.filter(e => e.propertyId === propertyId);
}

export function getPriceRecordsByProperty(propertyId: string): PriceRecord[] {
  return priceRecords.filter(p => p.propertyId === propertyId);
}

export function getAvailabilityByProperty(propertyId: string): AvailabilityRecord[] {
  return availabilityRecords.filter(a => a.propertyId === propertyId);
}

export function getMappingsByProperty(propertyId: string): Mapping[] {
  return mappings.filter(m => m.propertyId === propertyId);
}
